name: Trigger Concourse on Push
on: [ push, workflow_dispatch ]
env:
  HOST: https://ci.jitx.com
  TEAM: main
  PIPELINE: stanzasite
  TOKEN: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
jobs:
  trigger-push:
    runs-on: ubuntu-latest
    env:
      RESOURCE: git--stanzasite
    steps:
      - name: Trigger Concourse resource check
        run: |
          URL="${HOST}/api/v1/teams/${TEAM}/pipelines/${PIPELINE}/resources/${RESOURCE}/check/webhook?webhook_token=${TOKEN}"
          echo Triggering: "${URL}"
          curl --silent --fail --show-error --location --request "POST" --url "${URL}"
